name: release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-22.04
    name: Build and push the image
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Tags
        id: docker-tags
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/bacalhau-project/lotus-filecoin-image
          tags: |
            type=ref,event=tag

      - name: Check out code
        uses: actions/checkout@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker-tags.outputs.tags }}
          labels: ${{ steps.docker-tags.outputs.labels }}
